spring:
  redis:
    port: 6379
    host: 127.0.0.1
  #  h2:
  #    console:
  #      enabled: true
  #  datasource:
  #    url: jdbc:h2:mem:springcoredb
  #    username: sa
  #    password:
  datasource:
    url: jdbc:mysql://springboot-db.craud3vucxol.ap-northeast-2.rds.amazonaws.com:3306/wewrite
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PW }}
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${{ secrets.MAIL_USERNAME }}
    password: ${{ secrets.MAIL_PW }}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

Logging.level:
  org.apache.coyote.http11: debug #http 요청 메시지 보기