spring:
  redis:
    port: 6379
    host: 52.78.51.198
    password: 1111
  datasource:
    url: jdbc:mysql://springboot-db.craud3vucxol.ap-northeast-2.rds.amazonaws.com:3306/wewrite
    username: binscot
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(Ur5dg3ssI0oSwjjopkz5GEsm9DKvJmr5GXJGRNq61UA=)
    password: ENC(M0HskvtElJ5w+Jj7BkFutgnzc83hs+4i)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

cloud:
  aws:
    credentials:
      accessKey: ENC(4K1X5dPf64S9tmvBv90oz5+KaFW2y6zkn4OgfoaPSwg=)
      secretKey: ENC(VEC9ehAlTyGv9a/gA6a7QyXQ6OraW1u3+1i5Qg2mcEuHsvPh235tWMfLlXtCtFIYVf8fRtoQ3jQ=)

    s3:
      bucket: binscot-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

#jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator